### ISSUE TITLE
Excalidraw images duplicated: light and dark versions are both present

### ISSUE THREAD

**Issue by travisaustin** [CIMSTA/obsidiosaurus#19]
When I embed an Excalidraw image to my documentation, both the dark and light versions of that image are imported to my Docusaurus website.

Here's a sample showing a page with a single embedded in Obsidian. When published to Docusaurus, two versions are included in the page at the same time.

Obsidian screen:

![CleanShot 2024-06-18 at 10 26 28](https://github.com/CIMSTA/obsidiosaurus/assets/1134334/0a532082-0316-4a9e-964f-6e051607598e)

Docusaurus website in light mode:

![CleanShot 2024-06-18 at 10 25 17](https://github.com/CIMSTA/obsidiosaurus/assets/1134334/bfa9e949-1e95-4a3e-91ea-9c568077ddfd)

Docusaurus website in dark mode:

![CleanShot 2024-06-18 at 10 25 21](https://github.com/CIMSTA/obsidiosaurus/assets/1134334/93fb23d0-72a6-4c7c-b464-9062e71e4738)

Firefox developer tools shows the image is in the DOM twice:

![CleanShot 2024-06-18 at 10 29 25](https://github.com/CIMSTA/obsidiosaurus/assets/1134334/3c3c51f9-9ea3-438d-820c-eff8d886ff56)

Has anyone else seen this?

**Comment by Mat4m0** [comment]
You need to add to your CSS:

```css
[data-theme='light'] img[src$='#dark'],
[data-theme='dark'] img[src$='#light'] {
  display: none;
}

```

In the [Docusaurus Docs](https://docusaurus.io/docs/markdown-features/assets#github-style-themed-images)

**Comment by travisaustin** [comment]
Thank you!
